Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.provider :virtualbox do |vb|
    vb.cpus = 1
    vb.memory = 1024
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"] 
    vb.gui = false
  end
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = 'ubuntu-01'
    vm1.vm.network :private_network, ip: "192.168.10.101"
    vm1.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = 'ubuntu-02'
    vm2.vm.network :private_network, ip: "192.168.10.102"
    vm2.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
    SHELL
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = 'ubuntu-03'
    vm3.vm.network :private_network, ip: "192.168.10.103"
    vm3.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
    SHELL
  end
  
end
