Vagrant.configure("2") do |config|

    (1..2).each do |i|
		config.vm.define "debian-0#{i}" do |node|
		  node.vm.box = "debian/bullseye64"
		  node.vm.hostname = "debian-node0#{i}"
		  node.vm.network "private_network", ip: "10.0.0.#{i}"
		  node.vm.provider "virtualbox" do |vb|
			  vb.memory = 1024
			  vb.cpus = 1
		  end
		  config.vm.provision :docker																	
		  config.vm.provision :docker_compose		  
		end
	end
	
  end
  
