Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "dev-ubuntu"
      vb.cpus = 1
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"] 
      vb.gui = false
  end

  config.vm.provision "shell", path: "vagrant_files/install.sh"
end
