Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  
  config.vm.network "forwarded_port", guest: 8081, host: 8008
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  
  config.vm.provider "virtualbox" do |vb|
	vb.name = "dev-docker"
	vb.cpus = 1
	vb.memory = 2048
	vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"] 
	vb.gui = false
  end
  
  config.vm.provision "shell", inline: <<-SHELL
	apt-get update && apt-get upgrade -y
  SHELL
 
  # config.vm.provision "docker" do |docker|													# Instalacja Dockera
    # docker.run "mysql",																		# Uruchomienie obrazu mysql
      # image: "mysql:latest",
      # args: "-p 3306:3306 -e MYSQL_ROOT_PASSWORD=test123"
    # docker.run "phpmyadmin",																	# Uruchomienie obrazu phpmyadmin
      # image: "phpmyadmin:latest",
      # args: "-p 8081:80 --link mysql:db"
  # end

  config.vm.provision "file",																	# Kopiowanie pliku na vm	
    source: "docker-compose.yml",
    destination: "/home/vagrant/docker-compose.yml"
	
  config.vm.provision :docker																	# Instalacja Dockera
  config.vm.provision :docker_compose, yml: "/home/vagrant/docker-compose.yml", run: "always"	# Instalacja i uruchomienie docker-compose 

end
